name: Publish to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate Notices
        run: npm run generate:notices

        - name: Commit and push changes
        run: |
          ACTOR_NAME=$(echo "${{ github.actor }}")
          USER_EMAIL=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" https://api.github.com/users/$ACTOR_NAME | jq -r ".email")
          
          # If the email is null (not publicly available), use a default one
          if [ "$USER_EMAIL" == "null" ]; then
            USER_EMAIL="actions@github.com"
          fi
      
          git config user.name "$ACTOR_NAME"
          git config user.email "$USER_EMAIL"
          git add -A
          git commit -m "chore: update NOTICES.md" || echo "No changes to commit"
          git push https://${{ secrets.GH_PAT }}@github.com/Krister-Johansson/gqlPrune.git HEAD:main
      

      - name: Setup .npmrc file to publish to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
